version: 2.1
orbs:
  node: circleci/node@1.0.1
jobs:
  build:
    executor:
      name: node/default
      tag: "12"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run build
      - run: npm run lint
