version: "2.1"
orbs:
  node: circleci/node@5
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run lint
