version: 2.1
orbs:
  node: circleci/node@1.0.1
jobs:
  build:
    executor:
      name: node/default
      tag: "8"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run build
      - run: npx --no-install tsc
      - run: npx --no-install eslint --ext js,ts .
      - run: >
          npx --no-install prettier --check
          '**/*.css'
          '**/*.ejs'
          '**/*.js'
          '**/*.json'
          '**/*.ts'
          '**/*.yml'
